
#ifndef PROTOTYPES_H
#define PROTOTYPES_H

#include <string.h>

void AboutGTKNSBClient (gpointer, guint, GtkWidget *), DisplayWP (), FillWPInfo (), PrintWP (GtkWidget *, gpointer *), PrintFormCh (GtkWidget *, gpointer *),
     DestroyDialog (GtkWidget *, gpointer), InitByTeam (), Select1Team (char), ManageVH (), ShowVs (), FindBS (), do_boxscore (), SetButtons (),
     CancelGame (GtkWidget *, gpointer *), put_details (gint), Play1Game (char), send_stats (int), GetStatsRLP (GtkWidget *, gpointer *),
     GetYearRLTT (GtkWidget *, gpointer *), GetYearRLRES (GtkWidget *, gpointer *), DestroyGetYearRLRES (GtkWidget *, gpointer *), DoAutoIR (),
     SpeedUpGame (GtkWidget *, gpointer *), SlowDownGame (GtkWidget *, gpointer *), ShowLineups (), DestroyGetYearRLTT (GtkWidget *, gpointer *),
     PrintPBYP (GtkWidget *, gpointer *), DoBoxscore (GtkWidget *, gpointer *), DSfinished (GtkWidget *, gpointer), GetIDs (), DoAutoStandings (),
     PrintUsers (GtkWidget *, gpointer *), PrintInjuryReport (GtkWidget *, gpointer *), PrintLU (GtkWidget *, gpointer *), put_details_auto (gint),
     PrintHelp (GtkWidget *, gpointer *), PrintBox (GtkWidget *, gpointer *), PrintNAcc (GtkWidget *, gpointer *), ShowBestSeasons (),
     PrintAbbrev (GtkWidget *, gpointer *), PrintBox (GtkWidget *, gpointer *), ShowPlayerPic (int), KillPlayerPics (), DestroyBS (GtkWidget *, gpointer *),
     PrintMVP (GtkWidget *, gpointer *), PrintCyYoung (GtkWidget *, gpointer *), PrintGoldGloves (GtkWidget *, gpointer *),
     PrintGPS (GtkWidget *, gpointer *), PrintBox (GtkWidget *, gpointer *), GetTeamTotals (), SpinnerChange (), SpinnerChangePre1 (),
     PrintNSBMVP (GtkWidget *, gpointer *), PrintNSBCyYoung (GtkWidget *, gpointer *), FindBT (GtkWidget *, gpointer *), SpinnerChangePre2 (),
     PrintNSBGoldGlove (GtkWidget *, gpointer *), PrintNSBSilverSlugger (GtkWidget *, gpointer *), DestroyGetStatsRLP (GtkWidget *, gpointer *),
     FillNSBMVP (), FillNSBCyYoung (), FillNSBGoldGlove (), FillNSBSilverSlugger (), PrintBestTeams (GtkWidget *, gpointer),
     PrintNSBGoldGloves (GtkWidget *, gpointer *), PrintNSBGPS (GtkWidget *, gpointer *), FillBestTeams (), SetGWinTitle (),
     PrintStats (GtkWidget *, gpointer), DestroydlgBox (GtkWidget *, gpointer *), RemovePlayer (GtkWidget *, gpointer *), DestroyAC (GtkWidget *, gpointer *),
     PrintCatL (GtkWidget *, gpointer), PrintStandings (GtkWidget *, gpointer *), PrintSilverSlugger (GtkWidget *, gpointer *),
     CBbutbg (GtkWidget *, gpointer *), CBbutbab (GtkWidget *, gpointer *), ShowPlayerStats (char *), ShowBestTeams (), ShowTDIB (int),
     CBbutbr (GtkWidget *, gpointer *), CBbutbh (GtkWidget *, gpointer *), PrintRLPlayerStats (GtkWidget *, gpointer), DestroyBT (GtkWidget *, gpointer *),
     CBbutb2b (GtkWidget *, gpointer *), CBbutb3b (GtkWidget *, gpointer *), toggle_method_h (GtkWidget *, gpointer *), PrintRookie (GtkWidget *, gpointer *),
     CBbutbhr (GtkWidget *, gpointer *), CBbutbbi (GtkWidget *, gpointer *), toggle_method_a (GtkWidget *, gpointer *), CTeam (GtkWidget *, gpointer *),
     CBbutbbb (GtkWidget *, gpointer *), CBbutbso (GtkWidget *, gpointer *), CBckyear (GtkWidget *, gpointer), toggle_method_o (GtkWidget *, gpointer *),
     CBbutbhp (GtkWidget *, gpointer *), CBbutbdp (GtkWidget *, gpointer *), CBckrandom (GtkWidget *, gpointer), toggle_method_0 (GtkWidget *, gpointer *),
     CBbutbsb (GtkWidget *, gpointer *), CBbutbcs (GtkWidget *, gpointer *), CBckteam (GtkWidget *, gpointer), SaveEOptions (GtkWidget *, gpointer *),
     CBbutbibb (GtkWidget *, gpointer *), CBbutbs (GtkWidget *, gpointer *), PrintSeriesStatus (GtkWidget *, gpointer *), PrintHOF (GtkWidget *, gpointer *),
     CBbutbsf (GtkWidget *, gpointer *), CBbutbba (GtkWidget *, gpointer *), PrintTDIB (GtkWidget *, gpointer), ResetOptions (GtkWidget *, gpointer *),
     CBbutbsa (GtkWidget *, gpointer *), CBbutboba (GtkWidget *, gpointer *), TDIB (int, int, int), CancelOptions (GtkWidget *, gpointer *),
     CBbutpg (GtkWidget *, gpointer *), CBbutpgs (GtkWidget *, gpointer *), TDIBFromMenu (gpointer, guint, GtkWidget *),
     CBbutpip (GtkWidget *, gpointer *), CBbutpw (GtkWidget *, gpointer *), GetTDIB (GtkWidget *, gpointer *), ActSusp (GtkWidget *, gpointer *),
     CBbutpl (GtkWidget *, gpointer *), CBbutps (GtkWidget *, gpointer *), DestroyTDIB (GtkWidget *, gpointer *), toggle_method_o2 (GtkWidget *, gpointer *),
     CBbutpbfp (GtkWidget *, gpointer *), CBbutph (GtkWidget *, gpointer *), ScoreSeasons (gpointer, guint, GtkWidget *),
     CBbutp2b (GtkWidget *, gpointer *), CBbutp3b (GtkWidget *, gpointer *), FindOff (GtkWidget *, gpointer *), FindPit (GtkWidget *, gpointer *),
     CBbutphr (GtkWidget *, gpointer *), CBbutpr (GtkWidget *, gpointer *), PrintBestSeasons (GtkWidget *, gpointer), FillBestSeasons (int),
     CBbutper (GtkWidget *, gpointer *), CBbutpbi (GtkWidget *, gpointer *), ValFormula (GtkWidget *, gpointer *), ValidChars (GtkWidget *, gpointer *),
     CBbutpcg (GtkWidget *, gpointer *), CBbutpgf (GtkWidget *, gpointer *), SaveFormula (GtkWidget *, gpointer *), LoadFormula (GtkWidget *, gpointer *),
     CBbutpsho (GtkWidget *, gpointer *), CBbutpsopp (GtkWidget *, gpointer *), toggle_method_02 (GtkWidget *, gpointer *),
     CBbutpsb (GtkWidget *, gpointer *), CBbutpcs (GtkWidget *, gpointer *), toggle_method_0s (GtkWidget *, gpointer *),
     CBbutpbb (GtkWidget *, gpointer *), CBbutpso (GtkWidget *, gpointer *), toggle_method_0n (GtkWidget *, gpointer *),
     CBbutpibb (GtkWidget *, gpointer *), CBbutpsh (GtkWidget *, gpointer *), toggle_method_h2 (GtkWidget *, gpointer *),
     CBbutpsf (GtkWidget *, gpointer *), CBbutpwp (GtkWidget *, gpointer *), toggle_method_a2 (GtkWidget *, gpointer *),
     CBbutpb (GtkWidget *, gpointer *), CBbutphb (GtkWidget *, gpointer *), ValPPFormula (GtkWidget *, gpointer *), ValSPFormula (GtkWidget *, gpointer *),
     CBbutpab (GtkWidget *, gpointer *), CBbutpera (GtkWidget *, gpointer *), ValRPFormula (GtkWidget *, gpointer *), LoadPPFormula (GtkWidget *, gpointer *),
     CBbutppct (GtkWidget *, gpointer *), CBbutpba (GtkWidget *, gpointer *), LoadSPFormula (GtkWidget *, gpointer *),
     CBbutfog (GtkWidget *, gpointer *), CBbutfopo (GtkWidget *, gpointer *), LoadRPFormula (GtkWidget *, gpointer *),
     CBbutfodp (GtkWidget *, gpointer *), CBbutfoa (GtkWidget *, gpointer *), SavePPFormula (GtkWidget *, gpointer *),
     CBbutfoe (GtkWidget *, gpointer *), CBbutfoavg (GtkWidget *, gpointer *), SaveSPFormula (GtkWidget *, gpointer *),
     CBbutf1g (GtkWidget *, gpointer *), CBbutf1po (GtkWidget *, gpointer *), SaveRPFormula (GtkWidget *, gpointer *),
     CBbutf1dp (GtkWidget *, gpointer *), CBbutf1a (GtkWidget *, gpointer *),
     CBbutf1e (GtkWidget *, gpointer *), CBbutf1avg (GtkWidget *, gpointer *),
     CBbutf2g (GtkWidget *, gpointer *), CBbutf2po (GtkWidget *, gpointer *),
     CBbutf2dp (GtkWidget *, gpointer *), CBbutf2a (GtkWidget *, gpointer *),
     CBbutf2e (GtkWidget *, gpointer *), CBbutf2avg (GtkWidget *, gpointer *),
     CBbutf3g (GtkWidget *, gpointer *), CBbutf3po (GtkWidget *, gpointer *),
     CBbutf3dp (GtkWidget *, gpointer *), CBbutf3a (GtkWidget *, gpointer *),
     CBbutf3e (GtkWidget *, gpointer *), CBbutf3avg (GtkWidget *, gpointer *),
     CBbutfsg (GtkWidget *, gpointer *), CBbutfspo (GtkWidget *, gpointer *),
     CBbutfsdp (GtkWidget *, gpointer *), CBbutfsa (GtkWidget *, gpointer *),
     CBbutfse (GtkWidget *, gpointer *), CBbutfsavg (GtkWidget *, gpointer *),
     CBbutfpg (GtkWidget *, gpointer *), CBbutfppo (GtkWidget *, gpointer *),
     CBbutfpdp (GtkWidget *, gpointer *), CBbutfpa (GtkWidget *, gpointer *),
     CBbutfpe (GtkWidget *, gpointer *), CBbutfpavg (GtkWidget *, gpointer *),
     CBbutfcg (GtkWidget *, gpointer *), CBbutfcpo (GtkWidget *, gpointer *),
     CBbutfcdp (GtkWidget *, gpointer *), CBbutfca (GtkWidget *, gpointer *),
     CBbutfce (GtkWidget *, gpointer *), CBbutfcavg (GtkWidget *, gpointer *),
     CBbutfcpb (GtkWidget *, gpointer *), CBbutfdhg (GtkWidget *, gpointer *),
     CBWC0 (GtkWidget *, gpointer *), CBWC1 (GtkWidget *, gpointer *), CBWC2 (GtkWidget *, gpointer *),
     CBdhNL (GtkWidget *, gpointer *), CBdhAL (GtkWidget *, gpointer *), PCscatDestroyDialog (GtkWidget *, gpointer *),
     CBscatDestroyDialog (GtkWidget *, gpointer *), *play_snd (void *), *SpeakPlayByPlay (), DestroySwin (GtkWidget *, gpointer *),
     CBdhAll (GtkWidget *, gpointer *), CBdhNo (GtkWidget *, gpointer *), PlayOK (GtkWidget *, gpointer *),
     CBsteambutton (GtkWidget *, gpointer *), PopulateTopLevel (), PopulateChildren (), PopulateChildren2S (),
     PopulateTopLevel1 (), PopulateChildren1 (), PopulateTopLevel2 (), PopulateChildren2 (), PopulateTopLevel3 (),
     PopulateChildren3 (), CBposbutton (GtkWidget *, GdkEventButton *, gpointer), CBckbutton (GtkWidget *, gpointer),
     ResetLDsp (GtkWidget *, gpointer), RLDsp (GtkWidget *, gpointer), *Wait4Challenge (), PopulateTopLevel2S (),
     MakeLineupChange (GtkWidget *, gpointer), CBplybutton (GtkWidget *, gpointer), CBckTN (GtkWidget *, gpointer), CBckALL (GtkWidget *, gpointer),
     CBcplybutton (GtkWidget *, gpointer), MakeLChange (GtkWidget *, gpointer),
     CBbatterbutton (GtkWidget *, gpointer), CBbr1button (GtkWidget *, gpointer),
     CBbr2button (GtkWidget *, gpointer), CBbr3button (GtkWidget *, gpointer), NSBSeriesTeamTotals (gpointer, guint, GtkWidget *),
     CBplayerbutton (GtkWidget *, gpointer), CBdhbuttony (GtkWidget *, gpointer *),
     CBdhbuty (GtkWidget *, gpointer *), CBdhbutn (GtkWidget *, gpointer *),
     CBrbuty (GtkWidget *, gpointer *), CBrbutn (GtkWidget *, gpointer *),
     CBdhbuttonn (GtkWidget *, gpointer *), ExchangeTeams (GtkWidget *, gpointer *),
     GetNSBID (GtkWidget *, gpointer data), ReturnOff (GtkWidget *, gpointer), BestTeams (),
     ReturnDef (GtkWidget *, gpointer), CBckbutDef (GtkWidget *, gpointer), SetUpSeries (gpointer, guint, GtkWidget *),
     CBlubutton (GtkWidget *, gpointer), FillTeamStats (GtkTextBuffer *), FillTeamTotals (GtkTextBuffer *),
     GrabID (GtkWidget *, gpointer), CBs1teambutton (GtkWidget *, gpointer), PlaySeries (gpointer, guint, GtkWidget *),
     TellServerTeams (char), UpdateTop (), SeeLineup (gint), ChangeLineup (gint), SeriesStatus (gpointer, guint, GtkWidget *),
     Help (gpointer, guint, GtkWidget *), OffensiveCommand (char *), DefensiveCommand (char *, gint),
     Abbrev (gpointer, guint, GtkWidget *),
     GIndS (gpointer, guint, GtkWidget *), FillRLPlayerStats (GtkTextBuffer *, char *, int, int),
     DisconnectFromServer (gpointer, guint, GtkWidget *), CanLineup (GtkWidget *, gpointer),
     PlayNSB1GameAgainstComputer (gpointer, guint, GtkWidget *), NAcc (gpointer, guint, GtkWidget *), HOF (gpointer, guint, GtkWidget *),
     MVP (gpointer, guint, GtkWidget *), CyYoung (gpointer, guint, GtkWidget *), GoldGlove (gpointer, guint, GtkWidget *),
     PlayNSB1GameAgainstHumanSameComputer (gpointer, guint, GtkWidget *), SilverSlugger (gpointer, guint, GtkWidget *),
     NSBMVP (gpointer, guint, GtkWidget *), NSBCyYoung (gpointer, guint, GtkWidget *), Rookie (gpointer, guint, GtkWidget *),
     NSBGoldGlove (gpointer, guint, GtkWidget *), NSBSilverSlugger (gpointer, guint, GtkWidget *),
     PlayNSB1GameAgainstHumanOverNetwork (gpointer, guint, GtkWidget *), SeasonAutoplayEx (),
     PlayNSBWatch1GameComputerVsComputer (gpointer, guint, GtkWidget *),
     PlayNSBPortionOfLeague (gpointer, guint, GtkWidget *), PlayNSB1GameOverNetwork (), SeasonAutoplayAS (), toggle_1CL (GtkWidget *, gpointer *),
     Quit (gpointer, guint, GtkWidget *), CheckTName (GtkEntry *, const gchar *, gint, gint *, gpointer), toggle_SP (GtkWidget *, gpointer *),
     SetUpLeague (), toggle_SL (GtkWidget *, gpointer *), toggle_SG (GtkWidget *, gpointer *), toggle_PP (GtkWidget *, gpointer *),
     SetUpLeagueChoices (gpointer, guint, GtkWidget *), toggle_TDIB (GtkWidget *, gpointer *), toggle_MPP (GtkWidget *, gpointer *),
     LeagueInjuryReport (gpointer, guint, GtkWidget *), toggle_IUC (GtkWidget *, gpointer *), toggle_AAY (GtkWidget *, gpointer *),
     SeasonAutoplayEst (gpointer, guint, GtkWidget *), Users (gpointer, guint, GtkWidget *), toggle_SND (GtkWidget *, gpointer *), 
     BestRLTeams (gpointer, guint, GtkWidget *), toggle_PBP (GtkWidget *, gpointer *), CreateTeam (),
     LeagueInjuryReport (gpointer, guint, GtkWidget *), CheckPName (GtkEntry *, const gchar *, gint, gint *, gpointer),
     LoadLeague (gpointer, guint, GtkWidget *), SaveLeague (gpointer, guint, GtkWidget *), GetAYear4RLResults (),
     SetUpTeamChoices (gpointer, guint, GtkWidget *), CheckEntry (GtkEntry *, const gchar *, gint, gint *, gpointer),
     NSBStandings (gpointer, guint, GtkWidget *), ShowTeamStats (), ShowTeamTotals (), GetAYear4RLTeamTotals (),
     NSBCategoryLeadersPS (gpointer, guint, GtkWidget *), NSBCategoryLeadersRS (gpointer, guint, GtkWidget *),
     NSBCategoryLeadersSeries (gpointer, guint, GtkWidget *), NSBSeriesByTeam (gpointer, guint, GtkWidget *),
     NSBLifetimeRS (gpointer, guint, GtkWidget *), NSBLifetimePS (gpointer, guint, GtkWidget *),
     NSBByTeam (gpointer, guint, GtkWidget *), NSBLifetimeByTeam (gpointer, guint, GtkWidget *),
     NSBRegularSeasonTeamTotals (gpointer, guint, GtkWidget *), RealLifeTeamTotals (gpointer, guint, GtkWidget *),
     NSBPostSeasonTeamTotals (gpointer, guint, GtkWidget *), ShowTeamTotals (int), UserCreatedTeamTotals (gpointer, guint, GtkWidget *),
     NSBRecordsPersonalGame (gpointer, guint, GtkWidget *), NSBRecordsPersonalSeason (gpointer, guint, GtkWidget *),
     NSBRecordsAllGame (gpointer, guint, GtkWidget *), NSBRecordsAllSeason (gpointer, guint, GtkWidget *),
     RealLifeSeasonResults (gpointer, guint, GtkWidget *), RealLifeCategoryLeaders (gpointer, guint, GtkWidget *),
     CategoryLeaders (gint), ShowCategoryLeaders (), Preferences (gpointer, guint, GtkWidget *),
     RealLifeByPlayer (gpointer, guint, GtkWidget *), SeeSetupStatus (GtkWidget *, gpointer),
     RealLifeByTeam (gpointer, guint, GtkWidget *), UserCreatedByTeam (gpointer, guint, GtkWidget *),
     WhoIsWaiting (gpointer, guint, GtkWidget *), AddName (gpointer, guint, GtkWidget *),
     RemoveName (gpointer, guint, GtkWidget *), setup_tree_view (GtkWidget *), setup_tree_view3 (GtkWidget *),
     item_toggled (GtkCellRendererToggle *, gchar *, gpointer), TeamSelected (GtkTreeSelection *),
     TellServerAboutLeague (GtkWidget *, gpointer), add_columns (GtkTreeView *), add_columns1 (GtkTreeView *),
     add_columns2 (GtkTreeView *), TeamSelected2 (GtkTreeSelection *), TeamPicked (GtkTreeSelection *),
     Add2TextWindow (char *, int), Add2PBPWindow (char *, int), add_columns3 (GtkTreeView *), add_columns2S (GtkTreeView *),
     print (char *), SelectTeams (char), setup_tree_uview1 (GtkWidget *), setup_tree_uview2 (GtkWidget *), GotEOError (),
     outMessage (char *message[5]), outEOMessage (char *message[5]), GotError (), TeamSelected2S (GtkTreeSelection *),
     DisplayTopHalf (int), EOMsgOK (GtkWidget *, gpointer), RLPlyPicked (GtkTreeSelection *), RLPitPicked (GtkTreeSelection *),
     Connect2NSBServer (int), CreateNSBID (int), nsb_init (), FillStandings (), FillLUInfo (), FillSeriesStatus (), NSBAutoPlay (),
     FillUserInfo (), FillInjuryInfo (), FillRLSeasonResults (), FillCategoryLeaders (), FillBoxInfo (),
     populate (), SetLeagueUnderWay (int), SetSeriesUnderWay (int), CheckEntryBS (GtkEntry *, const gchar *, gint, gint *, gpointer),
     CheckEntryForm (GtkEntry *, const gchar *, gint, gint *, gpointer), CheckEntryMIN (GtkEntry *, const gchar *, gint, gint *, gpointer),
     CheckPPEntryForm (GtkEntry *, const gchar *, gint, gint *, gpointer), CheckSPEntryForm (GtkEntry *, const gchar *, gint, gint *, gpointer),
     CheckRPEntryForm (GtkEntry *, const gchar *, gint, gint *, gpointer);

int GetUserInfo (), Connect2Server (), InOutLeague (), ShallWeContinue (gchar *message[5]), SetUp2PlayGame (char), ValidateFormula (gchar *, int, int),
    delete_event (GtkWidget *, GdkEventConfigure *), get_stats (int, char, int), PlayTheGame (), DoLineup (int), ValidateTextBS (), DoAutoCatLeaders (int),
    delete_dlg (GtkWidget *, GdkEventConfigure *), HowMuchLeague (), GetRequestee (), ValidateText (), ValidateText2 (), ValidateText3 (), CheckLock (),
    DoStartingLineup (char), GetServerName (), isnanf (float), GetTeamFileName (int), isalpha (int), isdigit (int), isblank (int),
    killlwin (GtkWidget *, GdkEventConfigure *), donot_delete_event (GtkWidget *, GdkEventConfigure *), PickAPlayer (),
    SelRandomTeams (), SelDesignatedHitter ();

gboolean PlayChallenger (), PlayNetGame ();

char *cuserid (char *), *cnvt_int2str (int, char), *GetTeamName (int), *do_average (int, int), *do_era (int, int, int),
     *check_stats (int, char), *figure_pos (gint), *strcasestr (char *, char *);

GtkTreeModel *create_model (), *create_model1 (), *create_model2 (), *create_model2S (), *create_model3 ();

#endif

